# 公開用リポジトリにpushする
name: Release

on:
  push:
    branches:
      - release

env:
  YARN_CACHE_FOLDER: .cache/yarn
  DEPLOY_ENV: CF_PAGES

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with:
          path: src

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Cache node_modules
        uses: actions/cache@v3.2.2
        id: yarn-cache
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-v2

      - name: Install dependencies
        run: yarn
        working-directory: ./src

      - name: Generate sites
        run: yarn generate
        working-directory: ./src

      - name: Git and SSH configurations
        env:
          PUBLIC_DEPLOYKEY: ${{ secrets.PUBLIC_DEPLOYKEY }}
        run: |
          echo "$PUBLIC_DEPLOYKEY" > ~/deploykey.pem
          chmod 600 ~/deploykey.pem
          git config --global user.email "digital@nada-sc.jp"
          git config --global user.name "Github Actions"
      - name: Push pages
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploykey.pem -o StrictHostKeyChecking=no -F /dev/
        run: |
          git clone git@github.com:NadaDigitalCommittee/SportsPublic.git
          cd SportsPublic
          if [ -e ./2022/ ]; then
            rm -r ./2022/
          fi
          mv ../src/dist/ ./2022/
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Deploy NadaDigitalCommittee/Sports2022@$GITHUB_SHA"
            git push origin main
          fi
